version: '3.9'
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart: always
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001
